# Generated by Django 4.1.7 on 2023-04-07 03:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photo1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="photo2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="photo3",
        ),
        migrations.RemoveField(
            model_name="product",
            name="photo4",
        ),
        migrations.CreateModel(
            name="ImgProduct",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="img/%Y/%m")),
                ("alt_text", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod_image",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
                "ordering": ("created_at",),
            },
        ),
    ]
