# Generated by Django 4.1.7 on 2023-04-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_photo1_remove_product_photo2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="/product_sample.jpg",
                null=True,
                upload_to="img/%Y/%m",
                verbose_name="Main Photo",
            ),
        ),
    ]
