# Generated by Django 4.1.7 on 2023-04-08 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_cover_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.IntegerField(default=0),
        ),
    ]
